#App name
spring.application.name=grievance-portal

#Server
server.port = 8080

#Database connection
spring.datasource.url = JDBC:mysql://localhost:3306/grievance_db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Art@#123

#JPA/Hibernate - this auto creates tables in database
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# File upload configuration
spring.servlet.multipart.enabled = true
spring.servlet.multipart.max-file-size = 5MB
spring.servlet.multipart.max-request-size = 10MB

#File storage location
file.upload-dir = C:/grievance-portal-api/uploads

#Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rahman.athar95@gmail.com
spring.mail.password=ryilgmslazmtzugq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Email Sender Details
app.email.from=rahman.athar95@gmail.com
app.email.from-name=Grievance Portal
